nome = str(input("Digite aqui seu nome completo: ")).strip()
print(f"Seu nome em MAIUSCULO é: {nome.upper()}")
print(f"Seu nome em minuscula é: {nome.lower()}")
print(f"Seu nome tem ao todo {len(nome)-nome.count(' ')} letras") 
print(f"Seu primeiro nome tem {nome.find(' ')} letras")